### ISSUE TITLE
Correct grammatical mistake in readme

### ISSUE THREAD

**Issue by parammittal16** [adobe/aem-core-cif-components#124]
### Expected Behaviour

The readme should be error-free.

### Actual Behaviour

Grammatical mistakes in the readme file.

#### Platform and Version

AEM 6.5

**Comment by parammittal16** [comment]
@herzog31 plz review and let me know if there are some mistakes here. Actually I am new to his repo and want to contribute this as part of Squashtoberfest 2019.

**Comment by herzog31** [comment]
@parammittal16 Thank you for your contribution. Under normal circumstances we would gladly accept your PR. However, since you want to contribute as part of Squashtoberfest 2019 we feel obligated to reject your contribution, since it does not meet the quality standards. Thank you for your understanding.
