### ISSUE TITLE
[request of clarification] Nested Product Pages

### ISSUE THREAD

**Issue by gbagliocap** [adobe/aem-core-cif-components#446]
Is it possible to organize products pages with a deep structure of pages? As far I can say from my test it is not possible because tab "Commerce" is not visible under depth level 6 preventing from configuring product slugs.

To clarify my question let say we have the path "/content/mt-store/language-masters/en/products/product-page" as root page of all product pages. I'm wondering if it's possible to create 
- "content/cassina/language-masters/en/products/product-page/cluster-1-page" with different products slugs configured

- "content/cassina/language-masters/en/products/product-page/cluster-1-page/product-1234" with single product slug configured; slug of this product should not be configured in the parent page.

Is the missing tab "Commerce" under certain page depth level an intended feature? Or with the presence of this tab all other features would work as expected anyway?

**Comment by martinbuergi** [comment]
Hi @gbagliocap, thank you for your feature request. The current version only supports pages on the same level, but we plan to support nested pages in one of the upcoming releases.

**Comment by realgpp** [comment]
Hi @martinbuergi ,
as far as I can see, by enabling the page properties dialog to configure the product/category id, the page resolution works as expected. But in this case the only changes needed would be in file PageTypeRenderConditionServlet.java:
`            return productPage != null && pagePath.contains(productPage.getPath());` 
instead of
 `            return productPage != null && productPage.getPath().equals(parentPage.getPath());`

and 

`            return categoryPage != null && categoryPage.getPath().equals(parentPage.getPath());`
 instead of
 `           return categoryPage != null && pagePath.contains(categoryPage.getPath());`

Maybe I am missing something in the overall picture?

**Comment by mhaack** [comment]
@realgpp this is only one part of the solution. You are right changing the PageTypeRenderConditionServlet will make the missing Commerce tab available and uses can create custom PDP/PLP templates and select products.

The other part is how custom PDP/PLP templates found if a product or category URL is requested. Here the SpecificPageServlet.java and SpecificPageServlet.java are used, together with UrlProvider.java. These must be adapted as well as they currently won't work with nested PDP/PLP templates.

Changes are not that complicated. We are happy to review the PR if you want to go ahead and implement it.

**Comment by realgpp** [comment]
Hi, 
I'm trying to push branch "feature/nested_pdp_plp" with no success because of a permission error:
`ERROR: Permission to adobe/aem-core-cif-components.git denied to realgpp.`
`fatal: Could not read from remote repository.`
`Please make sure you have the correct access rights and the repository exists.
`

You need to grant me write permission? Or maybe there is something I need to do first?

**Comment by mhaack** [comment]
@realgpp we are happy to review your PR. The recommended way for contributions is, like for many other projects, to fork the repository and create a PR from there.
