### ISSUE TITLE
Ability to control how product URLs are displayed/chosen

### ISSUE THREAD

**Issue by froggin** [adobe/aem-core-cif-components#492]
### User Story
- As a user, I want to have full control over how a product URL looks, so that I can use the CIF connector on an existing product site without changing anything from an SEO perspective, or from a marketing perspective.

### Description & Motivation
- Whoever is using the CIF library would like full control over how product pages respond, or category pages. This motivation came from a client using the CIF library and was unable to do this - workarounds were implemented for this client, but I thought it would be much cleaner if a `UrlDelegator` could be used to choose which `UrlProvider` to use. This way, custom client-specific code can be used to implement the `UrlProvider` class and the `UrlDelegator` will be able to use theirs or the default provider based on priority. 

### Deliverables
- Make a `UrlDelegator` class so that custom versions of the `UrlProvider` can be implemented for client-specific product-name handling. The documentation would need to reflect that people can implement their own `UrlProvider` methods. The `shouldProcess` method of the `UrlProvider` will determine if the custom version should be used on a case-by-case basis. 

### Acceptance Criteria
- A user of the CIF library should be able to have product pages be whatever page they want. If they have a custom/existing page template type, they should not have to modify the URL structure to make it work with CIF. An implementor can help write custom logic to define what the product-key is for any of their custom pages, which would then pull in the product on the page with the customer's existing URL structure.

### Verification Steps
- Implement your own version of the `UrlProvider` and set the ranking to the min value so it is used first. Validate that product info is coming into your page(s) and test out with categories as well, according to your implementation.

**Comment by Buuhuu** [comment]
We did some major improvements in this area

a) since https://github.com/adobe/aem-core-cif-components/pull/738 customers can implement custom ProductUrlFromats and CategoryUrlFormats using the typical product attributes for that (url_key, url_path, sku, etc.)
b) since https://github.com/adobe/aem-core-cif-components/pull/792 and with a recent version of the Commerce AddOn it is now also possible to select the product/category url format per store (using the context aware CIF Configuration)

This in combination with Sling Mappings allows for the flexibility necessary for your described use case.
